server:
  port: 10088
  servlet:
    context-path: /poweyes

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poweyes?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: poweyes
    password: 123456


  redis:
    port: 6379
    host: 127.0.0.1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


poweyes:
  showCenter: 10086
  tokenFormat: poweyes